import { Geist, Geist_Mono } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import BootstrapClient from "../components/BootstrapClient";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export async function generateMetadata() {
  try {
    const res = await fetch(
      `${process.env.NEXT_PUBLIC_BASE_URL}/api/seo`,
      { cache: "no-store" }
    );

    if (!res.ok) {
      return {
        title: "Sivam One Way Taxi",
        description: "Affordable one way taxi service",
      };
    }

    const data = await res.json();

    return {
      title: data.meta_title || "Sivam One Way Taxi",
      description:
        data.meta_description || "Best outstation taxi service",
      keywords: data.meta_keywords || "",
    };
  } catch (err) {
    return {
      title: "Sivam One Way Taxi",
      description: "Reliable cab booking service",
    };
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <BootstrapClient />
        <Header />
        <main className="main">
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
